---
title: "webGL 3D rgl"
author: "Klinkenberg"
date: "2/18/2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Dropbox/UvA/Rmd/webGL")

library(knitr)
library(rgl)
knit_hooks$set(webgl = hook_webgl)
```

## webGL { .vcenter}

```{r, webgl=TRUE, echo=FALSE}
# open3d()
## 3d plot package rgl
## install.packages('rgl')
library("rgl")

load("moderation.rdata")
attach(data)

#1 #D scatter 

plot3d(predictor, moderator, outcome, 
       #col  = rainbow(100), 
       col  = "red",
       size = 8)
```

## Moderator values

```{r, webgl=TRUE, echo=FALSE}

#2 Planes

quantiles <- as.vector(quantile(moderator,seq(.1,.9,.1)))
sds       <- c(mean(moderator)+(sd(moderator)*c(-1,0,1)))  

planes3d(a = 0, 
         b = 1, 
         c = 0,
         d = -sds,
         #d = -quantiles,
         alpha=0.7,
         color = c("blue"))
```

## Multiple

```{r, webgl=TRUE, echo=FALSE, message=FALSE}
clear3d()

par3d(mouseMode = "zAxis")

mfrow3d(1, 2, sharedMouse = TRUE)

plot3d(predictor, moderator, outcome, 
       #col  = rainbow(100), 
       col  = "red",
       size = 8)

next3d()

plot3d(predictor, moderator, outcome, 
       #col  = rainbow(100), 
       col  = "red",
       size = 8)

planes3d(a = 0, 
         b = 1, 
         c = 0,
         d = -sds,
         #d = -quantiles,
         alpha=0.7,
         color = c("blue"))
```

## Regression plane

```{r, webgl=TRUE, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE,prompt=FALSE,comment=FALSE, highlight=FALSE, R.options=FALSE}
#3 Model surface  
rgl.close()

par3d(mouseMode = "zAxis")

plot3d(predictor, moderator, outcome, 
       #col  = rainbow(100), 
       col  = "red",
       size = 8)

planes3d(a = 0, 
         b = 1, 
         c = 0,
         d = -sds,
         #d = -quantiles,
         alpha=0.7,
         color = c("blue"))

#fit2 <- lm(outcome ~ predictor + moderator)
fit <- lm(outcome ~ predictor + moderator + predictor*moderator)
# summary(fit)

regeq <- function(model, predictor, moderator) { 
  fit$coefficients[1] + 
    fit$coefficients[2]*predictor + 
    fit$coefficients[3]*moderator + 
    fit$coefficients[4]*predictor*moderator
}

x.pre <- seq(10,21,length.out=30)
y.mod <- seq( 0,16,length.out=30)

z.pre <- outer(x.pre, y.mod, FUN='regeq', model=fit)

## Add 3D regression plane to scatter plot 
surface3d(x.pre,y.mod,z.pre, color = c("green"))

aspect3d(1,1,1)
```

